# This is a basic sample of how to use github actions
# I referenced https://www.youtube.com/watch?v=eUqUBMbmrfQ as the start of my education
# And will likely use it drive my CI learning

name: Test CI

# Controls when the workflow runs
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # A workflow run is made up of one or more jobs that can be run sequentially or in parallel
  jobs:
    #a particular job
    job-sample:
      #type of environment/machine
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3

      - name: run a one-line script
        run: echo Hello, world!

      - name: run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project

